{
  "uuid": "5e207d70-0f0a-4e2b-9385-37735da7090d-tr-0-1003",
  "historyId": "WhiteCase.CompApp.UiTests.Scenarios.Sample_AllureReportTypes.SimpleTestFailed",
  "fullName": "WhiteCase.CompApp.UiTests.Scenarios.Sample_AllureReportTypes.SimpleTestFailed",
  "labels": [
    {
      "name": "thread",
      "value": "NonParallelWorker"
    },
    {
      "name": "host",
      "value": "AGEORGE01"
    },
    {
      "name": "testClass",
      "value": "WhiteCase.CompApp.UiTests.Scenarios.Sample_AllureReportTypes"
    },
    {
      "name": "testMethod",
      "value": "SimpleTestFailed"
    },
    {
      "name": "package",
      "value": "WhiteCase.CompApp.UiTests.Scenarios.Sample_AllureReportTypes"
    },
    {
      "name": "owner",
      "value": "unickq"
    },
    {
      "name": "suite",
      "value": "FailedSuite"
    },
    {
      "name": "subSuite",
      "value": "DoesNotThrow"
    },
    {
      "name": "subSuite",
      "value": "AllureReportTypeSamples"
    }
  ],
  "links": [
    {
      "name": "Google",
      "url": "https://google.com",
      "type": "link"
    }
  ],
  "name": "SimpleTestFailed",
  "status": "failed",
  "statusDetails": {
    "known": false,
    "muted": false,
    "flaky": false,
    "message": "  Expected: No Exception to be thrown\r\n  But was:  <System.Exception: I'm an exception\r\n   at WhiteCase.CompApp.UiTests.Scenarios.Sample_AllureReportTypes.<>c.<SimpleTestFailed>b__3_0() in C:\\Users\\Ajith.George\\Desktop\\STUDY\\Selenium-WebDriver\\Reporting\\NunitWithAllureReporting_Version1\\NunitWithAllureReporting_Version1\\Sample_AllureReportTypes.cs:line 52\r\n   at NUnit.Framework.Constraints.ThrowsConstraint.VoidInvocationDescriptor.Invoke()\r\n   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>\r\n",
    "trace": "   at WhiteCase.CompApp.UiTests.Scenarios.Sample_AllureReportTypes.SimpleTestFailed() in C:\\Users\\Ajith.George\\Desktop\\STUDY\\Selenium-WebDriver\\Reporting\\NunitWithAllureReporting_Version1\\NunitWithAllureReporting_Version1\\Sample_AllureReportTypes.cs:line 50\r\n"
  },
  "stage": "finished",
  "description": "OLOLO\n",
  "steps": [
    {
      "name": "SimpleTestFailed",
      "status": "failed",
      "statusDetails": {
        "known": false,
        "muted": false,
        "flaky": false,
        "message": "  Expected: No Exception to be thrown\r\n  But was:  <System.Exception: I'm an exception\r\n   at WhiteCase.CompApp.UiTests.Scenarios.Sample_AllureReportTypes.<>c.<SimpleTestFailed>b__3_0() in C:\\Users\\Ajith.George\\Desktop\\STUDY\\Selenium-WebDriver\\Reporting\\NunitWithAllureReporting_Version1\\NunitWithAllureReporting_Version1\\Sample_AllureReportTypes.cs:line 52\r\n   at NUnit.Framework.Constraints.ThrowsConstraint.VoidInvocationDescriptor.Invoke()\r\n   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>\r\n",
        "trace": "   at WhiteCase.CompApp.UiTests.Scenarios.Sample_AllureReportTypes.SimpleTestFailed() in C:\\Users\\Ajith.George\\Desktop\\STUDY\\Selenium-WebDriver\\Reporting\\NunitWithAllureReporting_Version1\\NunitWithAllureReporting_Version1\\Sample_AllureReportTypes.cs:line 50\r\n"
      },
      "stage": "finished",
      "steps": [],
      "attachments": [
        {
          "name": "Console Output",
          "source": "7ced1ed6d1ec4fb3a75adb7eb90df9c7-attachment.txt",
          "type": "text/plain"
        }
      ],
      "parameters": [],
      "start": 1569944184475,
      "stop": 1569944184606
    }
  ],
  "attachments": [],
  "parameters": [],
  "start": 1569944184473,
  "stop": 1569944184615
}