{
  "uid" : "154b2ebd5d6156d8",
  "name" : "SimpleTestFailed",
  "fullName" : "AllureSample.Sample_AllureReportTypes+TestClass.SimpleTestFailed",
  "historyId" : "AllureSample.Sample_AllureReportTypes+TestClass.SimpleTestFailed",
  "time" : {
    "start" : 1569925991132,
    "stop" : 1569925991208,
    "duration" : 76
  },
  "description" : "OLOLO\n",
  "descriptionHtml" : "<p>OLOLO</p>\n",
  "status" : "failed",
  "statusMessage" : "  Expected: No Exception to be thrown\r\n  But was:  <System.Exception: I'm an exception\r\n   at AllureSample.Sample_AllureReportTypes.TestClass.<>c.<SimpleTestFailed>b__3_0() in C:\\Users\\Ajith.George\\Desktop\\STUDY\\Selenium-WebDriver\\Reporting\\NunitWithAllureReporting_Version1\\NunitWithAllureReporting_Version1\\Sample_AllureReportTypes.cs:line 54\r\n   at NUnit.Framework.Constraints.ThrowsConstraint.VoidInvocationDescriptor.Invoke()\r\n   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>\r\n",
  "statusTrace" : "   at AllureSample.Sample_AllureReportTypes.TestClass.SimpleTestFailed() in C:\\Users\\Ajith.George\\Desktop\\STUDY\\Selenium-WebDriver\\Reporting\\NunitWithAllureReporting_Version1\\NunitWithAllureReporting_Version1\\Sample_AllureReportTypes.cs:line 52\r\n",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "SetUp",
    "time" : {
      "start" : 1569925991192,
      "stop" : 1569925991192,
      "duration" : 0
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "hasContent" : false,
    "attachmentsCount" : 0,
    "shouldDisplayMessage" : false
  } ],
  "testStage" : {
    "description" : "OLOLO\n",
    "status" : "failed",
    "statusMessage" : "  Expected: No Exception to be thrown\r\n  But was:  <System.Exception: I'm an exception\r\n   at AllureSample.Sample_AllureReportTypes.TestClass.<>c.<SimpleTestFailed>b__3_0() in C:\\Users\\Ajith.George\\Desktop\\STUDY\\Selenium-WebDriver\\Reporting\\NunitWithAllureReporting_Version1\\NunitWithAllureReporting_Version1\\Sample_AllureReportTypes.cs:line 54\r\n   at NUnit.Framework.Constraints.ThrowsConstraint.VoidInvocationDescriptor.Invoke()\r\n   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>\r\n",
    "statusTrace" : "   at AllureSample.Sample_AllureReportTypes.TestClass.SimpleTestFailed() in C:\\Users\\Ajith.George\\Desktop\\STUDY\\Selenium-WebDriver\\Reporting\\NunitWithAllureReporting_Version1\\NunitWithAllureReporting_Version1\\Sample_AllureReportTypes.cs:line 52\r\n",
    "steps" : [ {
      "name" : "SimpleTestFailed",
      "time" : {
        "start" : 1569925991133,
        "stop" : 1569925991202,
        "duration" : 69
      },
      "status" : "failed",
      "statusMessage" : "  Expected: No Exception to be thrown\r\n  But was:  <System.Exception: I'm an exception\r\n   at AllureSample.Sample_AllureReportTypes.TestClass.<>c.<SimpleTestFailed>b__3_0() in C:\\Users\\Ajith.George\\Desktop\\STUDY\\Selenium-WebDriver\\Reporting\\NunitWithAllureReporting_Version1\\NunitWithAllureReporting_Version1\\Sample_AllureReportTypes.cs:line 54\r\n   at NUnit.Framework.Constraints.ThrowsConstraint.VoidInvocationDescriptor.Invoke()\r\n   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>\r\n",
      "statusTrace" : "   at AllureSample.Sample_AllureReportTypes.TestClass.SimpleTestFailed() in C:\\Users\\Ajith.George\\Desktop\\STUDY\\Selenium-WebDriver\\Reporting\\NunitWithAllureReporting_Version1\\NunitWithAllureReporting_Version1\\Sample_AllureReportTypes.cs:line 52\r\n",
      "steps" : [ ],
      "attachments" : [ {
        "uid" : "14bcf5fb6c040e1",
        "name" : "Console Output",
        "source" : "14bcf5fb6c040e1.txt",
        "type" : "text/plain",
        "size" : 41
      } ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "hasContent" : true,
      "attachmentsCount" : 1,
      "shouldDisplayMessage" : true
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 1,
    "hasContent" : true,
    "attachmentsCount" : 1,
    "shouldDisplayMessage" : false
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "thread",
    "value" : "NonParallelWorker"
  }, {
    "name" : "host",
    "value" : "AGEORGE01"
  }, {
    "name" : "testClass",
    "value" : "AllureSample.Sample_AllureReportTypes+TestClass"
  }, {
    "name" : "testMethod",
    "value" : "SimpleTestFailed"
  }, {
    "name" : "package",
    "value" : "AllureSample.Sample_AllureReportTypes+TestClass"
  }, {
    "name" : "owner",
    "value" : "unickq"
  }, {
    "name" : "suite",
    "value" : "FailedSuite"
  }, {
    "name" : "subSuite",
    "value" : "DoesNotThrow"
  }, {
    "name" : "subSuite",
    "value" : "AllureReportTypeSamples"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ {
    "name" : "Google",
    "url" : "https://google.com",
    "type" : "link"
  } ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "owner" : "unickq",
    "retries" : [ {
      "uid" : "d78135c9056f4474",
      "status" : "failed",
      "statusDetails" : "  Expected: No Exception to be thrown\r\n  But was:  <System.Exception: I'm an exception\r\n   at AllureSample.Sample_AllureReportTypes.TestClass.<>c.<SimpleTestFailed>b__3_0() in C:\\Users\\Ajith.George\\Desktop\\STUDY\\Selenium-WebDriver\\Reporting\\NunitWithAllureReporting_Version1\\NunitWithAllureReporting_Version1\\Sample_AllureReportTypes.cs:line 54\r\n   at NUnit.Framework.Constraints.ThrowsConstraint.VoidInvocationDescriptor.Invoke()\r\n   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>\r\n",
      "time" : {
        "start" : 1569925896954,
        "stop" : 1569925897033,
        "duration" : 79
      }
    }, {
      "uid" : "2beb74b39f41be66",
      "status" : "failed",
      "statusDetails" : "  Expected: No Exception to be thrown\r\n  But was:  <System.Exception: I'm an exception\r\n   at AllureSample.Sample_AllureReportTypes.TestClass.<>c.<SimpleTestFailed>b__3_0() in C:\\Users\\Ajith.George\\Desktop\\STUDY\\Selenium-WebDriver\\Reporting\\NunitWithAllureReporting_Version1\\NunitWithAllureReporting_Version1\\Sample_AllureReportTypes.cs:line 54\r\n   at NUnit.Framework.Constraints.ThrowsConstraint.VoidInvocationDescriptor.Invoke()\r\n   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>\r\n",
      "time" : {
        "start" : 1569925776957,
        "stop" : 1569925777052,
        "duration" : 95
      }
    } ],
    "categories" : [ {
      "name" : "Product defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "154b2ebd5d6156d8.json",
  "parameterValues" : [ ]
}